AWSTemplateFormatVersion: 2010-09-09
Description: "Stack for S3 bucket where artifacts will be stored"

Parameters:
  ProjectName:
    Description: Name of the project
    Type: String
  Environment:
    Description: Name of the stack environment
    Type: String

Resources:
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-artifacts-${Environment}
    DeletionPolicy: Retain