AWSTemplateFormatVersion: 2010-09-09
Description: "Stack for S3 bucket where artifacts will be stored"

Parameters:
  ProjectName:
    Description: Name of the project
    Type: String
  Environment:
    Description: Name of the stack environment
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod

Resources:
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-artifacts-${Environment}
      PublicAccessBlockConfiguration: 
        RestrictPublicBuckets: true
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
    DeletionPolicy: Delete

Outputs:
  BucketName:
    Value: !Ref 'ArtifactsBucket'
    Description: Bucket that holds authorized keys