AWSTemplateFormatVersion: 2010-09-09
Description: RDS DB

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  Subnets:
    Description: List of private subnet groups
    Type: List<AWS::EC2::Subnet::Id>
  InstanceType:
    Default: db.t2.micro
    Description: Instance type
    Type: String
  DBUsername:
    NoEcho: 'true'
    Description: Username for PostgreSQL database access
    Type: String
  DBPassword:
    NoEcho: 'true'
    Description: Password PostgreSQL database access
    Type: String
  DBPort:
    Description: The database port
    Type: String
    Default: 5432
  Environment:
    Description: Name of the stack environment
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod

Conditions:
  isProd: !Equals [ !Ref Environment, prod ]

Resources:
  MyDB:
    Type: 'AWS::RDS::DBInstance'
    DependsOn: MyDBSubnetGroup
    Properties:
      DBInstanceIdentifier: !Sub ${AWS::StackName}-master
      DBName: projectdb
      DBInstanceClass: !Ref InstanceType
      AllocatedStorage: !If [ isProd, 20, 5]
      Engine: postgres
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      Port: !Ref DBPort
      BackupRetentionPeriod: 1
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      PubliclyAccessible: 'false'
      VPCSecurityGroups: 
        - !GetAtt DBEC2SecurityGroup.GroupId
      Tags: 
        - 
          Key: Name
          Value: !Sub ${AWS::StackName}

  MyDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupName: !Sub ${AWS::StackName}-subnet-group
      DBSubnetGroupDescription: description
      SubnetIds: !Ref Subnets
  
  DBClientSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${AWS::StackName}-client
      GroupDescription: "Security group that can be used by clients to access DB (ie lambdas)"
      VpcId: !Ref VpcId
  
  DBEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${AWS::StackName}-ingress
      GroupDescription: "Enables access to the catalog database from outside"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref DBPort
          ToPort: !Ref DBPort
          SourceSecurityGroupId: !Ref DBClientSecurityGroup

Outputs:
  ClientSecurityGroup:
    Value: !Ref DBClientSecurityGroup
    Description: Security group required to access RDS
  MasterAddress:
    Value: !GetAtt MyDB.Endpoint.Address
  MasterPort:
    Value: !GetAtt MyDB.Endpoint.Port